version: '3.1'
services: 
    server:
        container_name: server_nlw03
        stdin_open: true # without this node doesn't start
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - 3333:3333
        volumes: 
            - .:/app
    